name: Dependabot Automation
on:
  pull_request:
    types: [opened, reopened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Assign to One Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        # if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
        with:
          project: https://github.com/users/TheFlyer1983/projects/1
          column_name: 'In Progress'